name: "Backbone in GitHub Actions"
description: "Start a Backbone Consumer API instance"

branding:
  icon: "star"
  color: "orange"

inputs:
  consumerapi-version:
    description: 'Consumer API version'
    required: true
  consumerapi-port:
    description: 'Consumer API port'
    required: false
    default: 5000

runs:
  using: "composite"
  steps:
    - shell: bash
      run: wget https://raw.githubusercontent.com/nmshd/backbone/capi/${CONSUMERAPI_VERSION}/setup-db/setup-postgres.sql
      env:
        CONSUMERAPI_VERSION: ${{ inputs.consumerapi-version }}
    - shell: bash
      run: docker compose up -d
      env:
        CONSUMERAPI_TAG: ${{ inputs.consumerapi-version }}
        PORT: ${{ inputs.consumerapi-port }}
